version: '3'
services:

  sidecar:
    image: hydrokhoos/ndn-all:arm
    # restart: always
    tty: true
    volumes:
      - ./sidecar/src/:/src/
      - data-volume:/data/
    ports:
      - "172.16.232.73:63633:6363/udp"

  service:
    # image: hydrokhoos/ubuntu-ndn-python
    build: ./service
    # restart: always
    tty: true
    volumes:
      - ./service/src/:/src/
      - data-volume:/data/

volumes:
  data-volume:
